config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'orders#index'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'}

  resources :orders
  resources :restaurants
  resources :calls, only: [:new, :create]
  resources :collects, only: [:create]
  resources :rates, only: [:create, :edit, :update]
  resources :products, only: [:create, :edit, :update, :show]

  get 'rate_products/new/:id', to: 'rates#new_product_rate', as: 'new_product_rate'
  get 'rate_restaurants/new/:id', to: 'rates#new_restaurant_rate', as: 'new_restaurant_rate'
  get 'profile/index'
  get 'products', to: 'products#index', as: 'products_index'
  get 'users', to: 'users#index', as: 'users_index'
  get 'users/:id', to: 'users#show', as: 'show_user'
  get 'search', to: 'application#search', as: 'search'
  get 'order_history', to: 'orders#history', as: 'orders_history'
  get 'your_profile', to: 'profile#index', as: 'user_profile'
  get 'order_stats', to: 'orders#stats', as: 'orders_stats'
  get 'rate_products', to: 'rates#rate_products', as: 'rate_products'
  get 'rate_restaurants', to: 'rates#rate_restaurants', as: 'rate_restaurants'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]
end

app/views/shared/_buttons.html.haml
.text-right.buttons-order
  - if user_signed_in? && @orders.exists?
    - if @today_call.exists? && @today_call.first.user_id == current_user.id
      = button_to "#{@today_call.first.estimated_time}", '#', class: 'btn btn-success order-now', disabled: true
    - elsif @today_call.exists?
      = button_to "#{@today_call.first.user.name} already called! \n#{@today_call.first.estimated_time}", '#', class: 'btn btn-success order-now', disabled: true
    - else
      = button_to "Call and order now!", new_call_path, class: 'btn btn-success order-now', data: { confirm: "Are you sure that you want to call and order today?"}, remote: true, method: :get
    - if @today_collect.exists? && @today_collect.first.user_id == current_user.id
      = button_to "You are collecting money today!", '#', class: 'btn btn-info order-now', disabled: true
    - elsif @today_collect.exists?
      = button_to "#{@today_collect.first.user.name} is collecting money today!", '#', class: 'btn btn-info order-now', disabled: true
    - else
      = button_to "I collect today money!", collects_path, class: 'btn btn-info order-now', data: { confirm: "Are you sure that you want to collect money today?"}, method: :post
    = link_to "Generate Orders as PDF", root_path(@orders, format: "pdf"), class: 'btn btn-danger', target: "_blank"

app/views/shared/_flash_messages.html.haml
.container
  .row
    .span6.offset3
      - flash.each do |type, message|
        %div{:class => "alert alert-#{type} fade in"}
          %button.close{"data-dismiss" => "alert"} ×
          = message

app/views/shared/_header.html.haml
.container
  .row-fluid
    .span10-offset1
      .hero-unit.text-center
        - if user_signed_in?
          %h1= "Welcome #{current_user.name}!"
          %br
          = image_tag(avatar_url(current_user), size: "100x100", class: 'border-photo')
          - if current_user.orders.where("created_at >= ?", Time.zone.now.beginning_of_day).length >= 1
            %br
            %br
            = button_to 'You ordered today! Please edit or delete your order if you want to add a new one!', new_order_path, method: :get, class: 'btn btn-primary', remote: true, disabled: true
          - else
            %h4
              %br
              Are you hungry :-) ?
            = button_to 'Add an order', new_order_path, method: :get, class: 'btn btn-primary', remote: true
        - else
          %h1 Order App
          %h4
            Welcome in the main page!
            %br
            Please login if you want to add new order.

app/views/shared/_navbar.html.haml
.navbar.navbar-inverse
  .navbar-inner
    .container{:style => "width: auto;"}
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .brand= link_to "Order App", root_path
      .nav-collapse
        %ul.nav
          - if user_signed_in?
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Orders
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to 'Today orders', root_path
                / %li
                /   = link_to 'Order stats', orders_stats_path
                %li.divider
                %li
                  = link_to 'Your orders history', orders_history_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Restaurants
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to 'Restaurants list', restaurants_path
              / %li
              /   = link_to 'Order stats', orders_stats_path
              %li.divider
              %li
                = link_to 'Rate Restaurants', rate_restaurants_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Products
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to 'Products list', products_path
              / %li
              /   = link_to 'Order stats', orders_stats_path
              %li.divider
              %li
                = link_to 'Rate Products', rate_products_path
          = link_to_active_li "Users", users_index_path
          %li.divider-vertical
          = form_tag search_path, :method => 'get', :class => "navbar-search pull-left" do
            = text_field_tag :query, nil, class: "search-query span2", placeholder: 'Search', "data-provide" => "typeahead", "data-source" => @typehead.to_json, :autocomplete => :off
            = link_to_submit fa_icon("search")
        - if user_signed_in?
          %ul.nav.pull-right
            %li
              .row.login-info
                = link_to image_tag(avatar_url(current_user), size: "20x20", class: 'border-photo'), "#"
                = link_to "Logged as #{current_user.name}", "#"
            %li.divider-vertical
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Profile
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to "Your profile", show_user_path(current_user.id)
                %li
                  = link_to "Edit profile", edit_user_registration_path
                %li.divider
                %li
                  = link_to 'Sign out', destroy_user_session_path, method: :delete
        - else
          %ul.nav.pull-right
            = link_to_active_li "Login", new_user_session_path
            = link_to_active_li "Sign up", new_user_registration_path
            %li
              %a{:href => "/auth/facebook"}
                %span.label.label-info.label-facebook
                  %i.fa.fa-facebook
                  | Login with Facebook