config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'orders#index'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'}

  resources :orders
  resources :restaurants
  resources :calls, only: [:new, :create]
  resources :collects, only: [:create]
  resources :rates, only: [:create, :edit, :update]
  resources :products, only: [:create, :edit, :update, :show]

  get 'rate_products/new/:id', to: 'rates#new_product_rate', as: 'new_product_rate'
  get 'rate_restaurants/new/:id', to: 'rates#new_restaurant_rate', as: 'new_restaurant_rate'
  get 'profile/index'
  get 'products', to: 'products#index', as: 'products_index'
  get 'users', to: 'users#index', as: 'users_index'
  get 'users/:id', to: 'users#show', as: 'show_user'
  get 'search', to: 'application#search', as: 'search'
  get 'order_history', to: 'orders#history', as: 'orders_history'
  get 'your_profile', to: 'profile#index', as: 'user_profile'
  get 'order_stats', to: 'orders#stats', as: 'orders_stats'
  get 'rate_products', to: 'rates#rate_products', as: 'rate_products'
  get 'rate_restaurants', to: 'rates#rate_restaurants', as: 'rate_restaurants'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  include PublicActivity::Common

  attr_accessor :creator

  has_and_belongs_to_many :users
  has_many :products
  has_many :rates
  has_many :orders

  validates :name, presence: true, uniqueness: true
  validates :short_info, presence: true
  validates :restaurant_type, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  TYPES = ["Chinese Restaurant", "Fast Food", "Cafe", "Pub", "Pizzeria", "Dinner"]

  def self.search(query)
    where("restaurant_type LIKE ? OR address LIKE ? OR name LIKE ? or short_info LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%")
  end

  def creator
    User.find(self.creator_id).try(:name)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < MethodsController
  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :typehead, expect: [:new, :edit, :show]
  before_action :restaurants_pagination, only: [:index, :create, :update, :destroy]

  def index
  end

  def new
    @restaurant = Restaurant.new
    render :show_form
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.creator_id = current_user.id
    if @restaurant.save
      @restaurant.create_activity :create, owner: current_user
      render :hide_form
    else
      render :show_form
    end
  end

  def edit
    render :show_form
  end

  def update
    if @restaurant.save
      @restaurant.update_attributes(restaurant_params)
      @restaurant.create_activity :update, owner: current_user
      render :hide_form
    else
      render :show_form
    end
  end

  def show
    @restaurant_map_params = "https://www.google.com/maps/embed/v1/place?key=AIzaSyA0rwZm3ycPPL_bwLo93jTnpTUWphpRmzs&q=" + @restaurant.latitude.to_s + "," + @restaurant.longitude.to_s + "&zoom=17"
  end

  def destroy
    @restaurant.create_activity :destroy, owner: current_user
    @restaurant.destroy
  end

  private

    def restaurant_params
      params.require(:restaurant).permit(:short_info, :name, :creator_id, :restaurant_type, :address, :latitude, :longitude)
    end

    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurants_pagination
      @restaurants = Restaurant.all
      @restaurants = @restaurants.order("name ASC")
      @restaurants = @restaurants.paginate(page: params[:page], per_page: 10)
    end
end

app/views/restaurants/_form.html.haml
#google-address{:onmouseover => "initialize()"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
    %h1
      = restaurant.new_record? ? "New restaurant" : "Edit #{restaurant.name}"
  = simple_form_for restaurant, class: 'clearfix', remote: true do |f|
    .modal-body
      = f.input :name, input_html: { class: 'form-control' }, label: 'Name', required: false
      = f.input :short_info, input_html: { class: 'form-control' }, label: 'Short info', required: false
      = f.input :restaurant_type, input_html: { class: 'form-control' }, label: 'Type', collection: Restaurant::TYPES, required: false
      = f.input :address, input_html: { id: "autocomplete", placeholder: "Enter an address", class: "address_input" }, label: 'Address', required: false
    .modal-footer
      %a.btn{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} Close
      = f.submit 'Submit', class: 'btn btn-primary'

app/views/restaurants/_header.html.haml
%h1.text-center
  Restaurant List
- if user_signed_in?
  .centered
    .button-add
      = button_to 'Add a new restaurant', new_restaurant_path, method: :get, class: 'btn btn-primary', remote: true
- else
  .centered
    %h3 Please login if you want to add new one or show existing.

app/views/restaurants/_restaurant_list.html.haml
#restaurants
  .container
    - if @restaurants.empty?
      .row
        .span6.offset3
          .alert.alert-info.text-center
            %button.close{"data-dismiss" => "alert", :type => "button"} &times;
            %strong Opsss...
            There are no restaurants added yet!
    - else
      %table.table.table-bordered.table-hover
        %thead
          %tr
            %th.span2 Name
            %th.span3 Short info
            %th.span2 Type
            %th.span1 Orders
            %th.span1 Avg. Rate
            - if user_signed_in?
              %th.span1 Actions
        %tbody
          - @restaurants.each do |restaurant|
            %tr
              %td.span2
                = restaurant.try(:name)
                - if user_signed_in?
                  - if restaurant.creator_id == current_user.id
                    %span.label.label-success You added
              %td.span3= restaurant.try(:short_info).truncate(40)
              %td.span2= restaurant.try(:restaurant_type)
              %td.span1= restaurant.try(:orders).count
              %td.span1= average_rate(restaurant)
              - if user_signed_in?
                %td.span1
                  = link_to restaurant_path(restaurant), remote: true do
                    = fa_icon "eye"
                  - if restaurant.creator_id == current_user.id
                    = link_to edit_restaurant_path(restaurant), remote: true do
                      = fa_icon "edit"
                    = link_to restaurant_path(restaurant), remote: true, method: :delete, data: { confirm: "Are you sure to delete #{restaurant.name}?"} do
                      = fa_icon "trash-o"
    .row
      .text-center.pagination
        = will_paginate @restaurants, renderer: BootstrapPagination::Rails, previous_label: "← Next", next_label: "Previous →"

app/views/restaurants/_restaurants_list.html.haml
- if restaurants.empty?
  %span.text-warning There are no restaurants!
- else
  %table.table.table-hover.table-border
    %thead
      %tr
        %th.span3 Name
        %th.span4 Short Info
        %th.span3 Type
        - if user_signed_in?
          %th.span2
    %tbody
      - restaurants.each do |restaurant|
        %tr
          %td.span3
            = restaurant.name
            - if user_signed_in?
              - if restaurant.user_id == current_user.id
                %span.label.label-success You added this one
          %td.span4= restaurant.short_info
          %td.span3= restaurant.restaurant_type
          - if user_signed_in?
            %td.span2
              = link_to restaurant_path(restaurant), remote: true do
                %i.icon-eye-open
              - if restaurant.user_id == current_user.id
                = link_to edit_restaurant_path(restaurant), remote: true do
                  %i.icon-edit
                = link_to restaurant_path(restaurant), remote: true, method: :delete, data: { confirm: "Na pewno chcesz usunąć #{restaurant.short_info}?"} do
                  %i.icon-remove

app/views/restaurants/_show_restaurant.html.haml
.modal-header
  %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
  %h1
    = restaurant.try(:name)
.modal-body
  %p
    %span.bold Who added:
    = restaurant.creator
  %p
    %span.bold Short info:
    = restaurant.try(:short_info)
  %p
    %span.bold Type:
    = restaurant.try(:restaurant_type)
  %p
    %span.bold Average Rate:
    = average_rate(restaurant)
  %p
    %span.bold Address:
    = restaurant.try(:address)
    %br
    %br
    - if restaurant.longitude
      %iframe{:frameborder => "0", :height => "500", :src => @restaurant_map_params, :style => "zoom:0.90", :width => "99.6%"}
.modal-footer
  %a.btn{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} Close

app/views/restaurants/destroy.js.erb
$('#flash-messages').html('<%= j(render partial: 'shared/flash_messages') %>');
$('#restaurant-list').html('<%= j(render partial: 'restaurants/restaurant_list', locals: { restaurants: @restaurants }) %>');

app/views/restaurants/hide_form.js.erb
$('#flash-messages').html('<%= j(render partial: 'shared/flash_messages') %>');
$('#restaurant-list').html('<%= j(render partial: 'restaurants/restaurant_list', locals: { restaurants: @restaurants })%>');
$('#modal').modal('hide');

app/views/restaurants/index.html.haml
:javascript
  $(function(){
     $('.pagination a').attr('data-remote', 'true')
  });

#header-main
  = render partial: 'header'
#flash-messages.container
  = render partial: 'shared/flash_messages', flash: flash
#restaurant-list
  = render partial: 'restaurants/restaurant_list'
#modal.modal.fade

app/views/restaurants/index.js.erb
$('#restaurants').html("<%= escape_javascript(render("restaurant_list"))%>")
$('.pagination a').attr('data-remote', 'true');

app/views/restaurants/show.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'show_restaurant', locals: {restaurant: @restaurant}) %>');
m.modal('show');

app/views/restaurants/show_form.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'form', locals: {restaurant: @restaurant}) %>');
m.modal('show');