config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'orders#index'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'}

  resources :orders
  resources :restaurants
  resources :calls, only: [:new, :create]
  resources :collects, only: [:create]
  resources :rates, only: [:create, :edit, :update]
  resources :products, only: [:create, :edit, :update, :show]

  get 'rate_products/new/:id', to: 'rates#new_product_rate', as: 'new_product_rate'
  get 'rate_restaurants/new/:id', to: 'rates#new_restaurant_rate', as: 'new_restaurant_rate'
  get 'profile/index'
  get 'products', to: 'products#index', as: 'products_index'
  get 'users', to: 'users#index', as: 'users_index'
  get 'users/:id', to: 'users#show', as: 'show_user'
  get 'search', to: 'application#search', as: 'search'
  get 'order_history', to: 'orders#history', as: 'orders_history'
  get 'your_profile', to: 'profile#index', as: 'user_profile'
  get 'order_stats', to: 'orders#stats', as: 'orders_stats'
  get 'rate_products', to: 'rates#rate_products', as: 'rate_products'
  get 'rate_restaurants', to: 'rates#rate_restaurants', as: 'rate_restaurants'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  include PublicActivity::Common

  belongs_to :user
  belongs_to :restaurant
  belongs_to :product

  validates :score, presence: true

  Scores = %w[1 2 3 4 5]
end

app/controllers/rates_controller.rb
class RatesController < MethodsController
  before_action :set_rate, only: [:edit, :update]
  before_action :typehead, only: [:create, :update, :rate_products, :rate_restaurants]

  def new_product_rate
    @rate = Rate.new
    @products_to_rate = collect_items(current_user.products)
    render :show_form
  end

  def new_restaurant_rate
    @rate = Rate.new
    @restaurants_to_rate = collect_items(current_user.restaurants)
    render :show_form
  end

  def create
    @rate = current_user.rates.build(rate_params)
    if @rate.save
      @rate.create_activity :create, owner: current_user
      if @rate.product_id.present?
        collect_items(current_user.products)
        render :hide_form_product
      else
        collect_items(current_user.restaurants)
        render :hide_form_restaurant
      end
    else
      render :show_form
    end
  end

  def edit
    render :show_form
  end

  def update
    if @rate.save
      @rate.create_activity :update, owner: current_user
      if @rate.product_id.present?
        @rate.update_attributes(rate_params)
        collect_items(current_user.products)
        render :hide_form_product
      else
        @rate.update_attributes(rate_params)
        collect_items(current_user.restaurants)
        render :hide_form_restaurant
      end
    end
  end

  def rate_products
    collect_items(current_user.products)
  end

  def rate_restaurants
    collect_items(current_user.restaurants)
  end

  private

    def rate_params
      params.require(:rate).permit(:score, :user_id, :restaurant_id, :product_id, :commment)
    end

    def set_rate
      @rate = Rate.find(params[:id])
    end

    def collect_items(objects)
      @to_rate, @rated = [], []
      objects.each do |object|
        object.rates.where(user_id: current_user.id).present? ? @rated << object : @to_rate << object
      end
    end
end

app/helpers/rates_helper.rb
module RatesHelper

  def rate(object)
    rate = object.rates.average(:score)
  end

  def find_rate(object)
    object.rates.where(user_id: current_user.id).first.id
  end

  def show_item_in_public_activity(object)
    object.product.present? ? object.product.name : object.restaurant.name
  end

  def user_rate(object)
    rate = object.rates.where(user_id: current_user.id)
    score = rate.present? ? rate.first.score.to_i : 0
    difference = 5 - score
    check_score(score, difference, score)
  end

  def average_rate(object)
    rates = object.rates.pluck(:score).inject(:+).to_i
    difference = 5 - rates
    if object.rates.present?
      draw_missing_stars(difference, rates)
    else
      "Not rated"
    end
  end

  def rate_score(object)
    score = object.score.to_i
    difference = 5 - score
    check_score(score, difference, score)
  end

  def check_score(object, difference, score)
    if object > 0
      draw_missing_stars(difference, score)
    else
      "Not rated"
    end
  end

  def draw_missing_stars(object, rates)
    if object > 0
      ("<i class='fa fa-star'></i>" * rates + "<i class='fa fa-star-o'></i>" * object).html_safe
    else
      ("<i class='fa fa-star'></i>" * rates).html_safe
    end
  end

end

app/views/rates/_form.html.haml
.modal-header
  %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
  %h1
    = rate.new_record? ? "New rate" : "Edit rate ##{rate.id}"
= simple_form_for rate, class: 'clearfix', remote: true do |f|
  .modal-body
    = f.input :score, label: 'Score', collection: Rate::Scores, required: false, input_html: { value: f.object.score.to_i || nil }
    = f.input :comment, input_html: { value: f.object.comment || nil }
    = f.input :product_id, collection: @products_to_rate, input_html: { value: params[:id] }, as: :hidden if @products_to_rate.present?
    = f.input :restaurant_id, collection: @restaurants_to_rate, input_html: { value: params[:id] }, as: :hidden if @restaurants_to_rate.present?
  .modal-footer
    %a.btn{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} Close
    = f.submit 'Submit', class: 'btn btn-primary'

app/views/rates/_product_list.html.haml
#products-list
  .container
    - if @to_rate.empty?
      .row
        .span6.offset3
          .alert.alert-info.text-center
            %button.close{"data-dismiss" => "alert", :type => "button"} &times;
            %strong Opsss...
            There are no available products to rate for now!
    - else
      %h1.text-center.header-padding Products to rate
      %table.table.table-bordered.table-hover
        %thead
          %tr
            %th.span2 Name
            %th.span3 Price
            %th.span2 Restaurant
            %th.span1 Average Rate
            - if user_signed_in?
              %th.span1 Add Rate
        %tbody
          - @to_rate.each do |product|
            %tr
              %td.span2= product.try(:name)
              %td.span3= number_to_currency(product.try(:price), unit: "zł", separator: ",", delimiter: "", format: "%n %u")
              %td.span2= product.try(:restaurant).try(:name)
              %td.span1= user_rate(product)
              - if user_signed_in?
                %td.span1
                  = link_to new_product_rate_path(product), remote: true do
                    = fa_icon "thumbs-up"
    - if @rated.present?
      %h1.text-center.header-padding Products rated by you
      %table.table.table-bordered.table-hover
        %thead
          %tr
            %th.span2 Name
            %th.span2 Price
            %th.span2 Restaurant
            %th.span1 Average Rate
            %th.span1 Your Rate
            - if user_signed_in?
              %th.span1 Edit Rate
        %tbody
          - @rated.each do |product|
            %tr
              %td.span2= product.try(:name)
              %td.span2= number_to_currency(product.try(:price), unit: "zł", separator: ",", delimiter: "", format: "%n %u")
              %td.span2= product.restaurant.name if product.restaurant
              %td.span1= average_rate(product)
              %td.span1= user_rate(product)
              - if user_signed_in?
                %td.span1
                  = link_to edit_rate_path(find_rate(product)), remote: true do
                    = fa_icon "edit"

app/views/rates/_restaurant_list.html.haml
#rate_restaurants
  .container
    - if @to_rate.empty?
      .row
        .span6.offset3
          .alert.alert-info.text-center
            %button.close{"data-dismiss" => "alert", :type => "button"} &times;
            %strong Opsss...
            There are no available restaurants to rate for now!
    - else
      %h1.text-center.header-padding Restaurants to rate
      %table.table.table-bordered.table-hover
        %thead
          %tr
            %th.span2 Name
            %th.span3 Short Info
            %th.span2 Restaurant Type
            %th.span1 Average Rate
            - if user_signed_in?
              %th.span1 Add Rate
        %tbody
          - @to_rate.each do |restaurant|
            %tr
              %td.span2= restaurant.try(:name)
              %td.span3= restaurant.try(:short_info)
              %td.span2= restaurant.try(:restaurant_type)
              %td.span1= average_rate(restaurant)
              - if user_signed_in?
                %td.span1
                  = link_to new_restaurant_rate_path(restaurant), remote: true do
                    = fa_icon "thumbs-up"
    - if @rated.present?
      %h1.text-center.header-padding Restaurants rated by you
      %table.table.table-bordered.table-hover
        %thead
          %tr
            %th.span2 Name
            %th.span2 Short Info
            %th.span2 Restaurant Type
            %th.span1 Average Rate
            %th.span1 Your Rate
            - if user_signed_in?
              %th.span1 Edit Rate
        %tbody
          - @rated.each do |restaurant|
            %tr
              %td.span2= restaurant.try(:name)
              %td.span2= restaurant.try(:short_info).truncate(35)
              %td.span2= restaurant.try(:restaurant_type)
              %td.span1= average_rate(restaurant)
              %td.span1= user_rate(restaurant)
              %td.span1
                = link_to edit_rate_path(find_rate(restaurant)), remote: true do
                  = fa_icon "edit"

app/views/rates/hide_form_product.js.erb
$('#flash-messages').html('<%= j(render partial: 'shared/flash_messages') %>');
$('#products-list').html('<%= j(render partial: 'product_list')%>');
$('#modal').modal('hide');

app/views/rates/hide_form_restaurant.js.erb
$('#flash-messages').html('<%= j(render partial: 'shared/flash_messages') %>');
$('#rate_restaurants').html('<%= j(render partial: 'restaurant_list')%>');
$('#modal').modal('hide');

app/views/rates/hide_form_restuarant.js.erb
$('#flash-messages').html('<%= j(render partial: 'shared/flash_messages') %>');
$('#flash-messages').html('<%= j(render partial: 'shared/flash_messages') %>');
$('#modal').modal('hide');

app/views/rates/rate_products.html.haml
= render partial: 'shared/flash_messages'
= render partial: 'product_list'
#modal.modal.fade

app/views/rates/rate_restaurants.html.haml
= render partial: 'shared/flash_messages'
= render partial: 'restaurant_list'
#modal.modal.fade

app/views/rates/show_form.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'form', locals: {rate: @rate}) %>');
m.modal('show');